### ISSUE TITLE
_haruto

### ISSUE THREAD

**Issue by monte02** [StaZarycki/Reff-Essentials#1]
JA PIERDOLE
CZEMU NA SHT NIE MOMŻE BYĆ CHOĆ W POŁOWIE TAK DOBRY POOL JAK NA JMT
ej pojebało kogoś
czemu mi nagle nero samo zaczęło hostować

**Comment by StaZarycki** [comment]
no mamy
2k18
więc
w sumie
nwm czas chyba
chuj nie pamiętam jak to sie mówi
krwa keidy ten facet z pratyk przyjdzie bo chce se hot doga kupić
